import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable()
class UserModel {
  UserModel();
  int? uid;
  String? nickname;
  String? realName;
  String? avatar;
  String? phone;
  int? addTime;
  int? lastTime;
  String? nowMoney;
  String? brokeragePrice;
  int? integral;
  String? exp;
  int? signNum;
  int? signRemind;
  int? status;
  int? level;
  int? agentLevel;
  int? spreadOpen;
  int? spreadUid;
  int? spreadTime;
  String? userType;
  int? isPromoter;
  int? payCount;
  int? spreadCount;
  String? loginType;
  String? birthday;
  String? cardId;
  String? mark;
  int? groupId;
  String? addres;
  bool? adminid;
  String? recordPhone;
  int? isMoneyLevel;
  int? isEverLevel;
  int? overdueTime;
  String? uniqid;
  int? divisionType;
  int? divisionStatus;
  int? isDivision;
  int? isAgent;
  int? isStaff;
  int? divisionId;
  int? agentId;
  int? staffId;
  int? divisionPercent;
  int? divisionChangeTime;
  int? divisionEndTime;
  int? divisionInvite;
  int? isDel;
  bool? isOpenMember;
  String? agentLevelName;
  int? isComplete;
  int? couponCount;
  int? like;
  // OrderStatusNum orderStatusNum;
  int? notice;
  int? recharge;
  String? orderStatusSum;
  int? extractTotalPrice;
  String? extractPrice;
  int? statu;
  int? brokenCommission;
  String? commissionCount;
  bool? vip;
  int? yesterDay;
  int? rechargeSwitch;
  // List<SwitchUserInfo> switchUserInfo;
  int? brokenDay;
  int? balanceFuncStatus;
  bool? invioceFunc;
  bool? specialInvoice;
  int? collectCount;
  bool? spreadStatus;
  bool? payVipStatus;
  int? memberStyle;
  int? vipStatus;
  bool? svipOpen;
  int? serviceNum;
  int? spreadLevelCount;
  List<String>? extractType;
  int? isAgentLevel;
  int? divisionOpen;
  int? agentApplyOpen;
  int? isDefaultAvatar;

  factory UserModel.fromJson(Map<String, dynamic> json) => _$UserModelFromJson(json);
  Map<String, dynamic> toJson() => _$UserModelToJson(this);
}
